%YAML 1.2
---
run_duration:
  description: Simulation run time
  value:
    type: float
    default: 100.
    units: y
    range:
      min: 0
      max: 1000000
---
_name: Grid

number_of_rows:
  description: Number of grid rows.
  value:
    type: int
    default: 1000
    range:
      min: 0
      max: 10000
    units: -

number_of_columns:
  description: Number of grid columns.
  value:
    type: int
    default: 500
    range:
      min: 0
      max: 10000
    units: -

row_spacing:
  description: Spacing between grid rows
  value:
    type: float
    default: 10
    range:
      min: 0
      max: 1000
    units: m

column_spacing:
  description: Spacing between grid columns.
  value:
    type: float
    default: 10
    range:
      min: 0
      max: 1000
    units: m
---
_name: Sea Level

initial_sea_level:
  description: Initial sea-level elevation
  value:
    type: float
    default: 0.
    range:
      min: -1000.
      max: 1000.
    units: m
rate_of_sea_level_rise:
  description: Rate of sea-level rise
  value:
    type: float
    default: 0.025
    range:
      min: -10.
      max: 10.
    units: m/yr
rate_of_inlet_rise:
  description: Rate that the inlet cell rises (subsidence)
  value:
    type: float
    default: 0.005
    range:
      min: -10.
      max: 10.
    units: m/yr
